### ISSUE TITLE
Error starting in dev mode

### ISSUE THREAD

**Issue by tylergraf** [alisd23/lazy-isomorphic-react#1]
I'm running node `5.6.0`. `npm install` worked fine but I get an error when I run `grunt serve:dev`

``` bash
Using tsc v1.7.5
/Users/tylergraf/Sites/lazy-isomorphic-react/typescript/universal/components/Product/ProductListPagination.tsx(35,5): error TS4091: Loop contains block-scoped variable 'i' referenced by a function in the loop. This is only supported in ECMAScript 6 or higher.

>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
Warning: Task "ts:default" failed. Use --force to continue.
```

Any idea what's going on?

**Comment by alisd23** [comment]
This is to do with a wrong typescript version, I've just pushed a fix (package.json now asks for typescript v1.8.0). If you pull then run npm install or update again that should work. Let me know if you have any issues. I rushed things a bit on friday so I might need to iron out some problems.

**Comment by tylergraf** [comment]
👍🏻
